#spring:
#  datasource:
#    url: jdbc:sqlite:./src/main/data/database.db
#    driver-class-name: org.sqlite.JDBC
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.SQLiteDialect
#      ddl-auto: update
#  hibernate:
#    dialect: org.hibernate.dialect.SQLiteDialect
spring:
  #  datasource:
  #    url: jdbc:h2:file:./src/main/data/database;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  #    driver-class-name: org.h2.Driver
  #    username: sa
  #    password:
  h2:
    console:
      enabled: true
  jpa:
    #    hibernate:
    #      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
logging:
  level:
    sql: debug
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

