spring:
  h2:
    console:
      enabled: true
  jpa:
    persistence-unit-name: testPU
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
logging:
  level:
    sql: debug
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
